-- AlterTable
ALTER TABLE "Order"
ADD COLUMN "shippingMethod" TEXT NOT NULL DEFAULT 'Unknown',
ADD COLUMN "shippingCost" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "total" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "OrderItem"
ADD COLUMN "color" TEXT NOT NULL DEFAULT '';
